### ISSUE TITLE
About the number of epoch for training on ShanghaiTech dataset.

### ISSUE THREAD

**Issue by linshuheng6** [cvlab-yonsei/MNAD#11]
Hi,
Thank you for your great word!
I try to reproduce the performance on the ShanghaiTech through the source code. The training settings are totally following the Implementation details. However, I only get AUC 67.8. 
The questions are below:
1. why can not I get AUC 72 on Shanghai Tech? My pytorch version is 1.1.0.
2. The training data in ShanghaiTech are more than that in Ped2 or Avenue, but the training epoch num is set as 10. Is it enough for convergence?

**Comment by hyunjp** [comment]
Hi, thanks for the attention to our work.

As the ShanghaiTech is large dataset, the number of iterations for one epoch is relatively bigger than other datasets.
We adjusted the number of epochs according to the number of iterations.

We cannot surely figure out what’s the problem of the low performance, but there are some variance of performances due to the stochastic learning.
You may have to learn the model for multiple times.

Thank you.
